from __future__ import annotations

import argparse
import json
from pathlib import Path

from .fixtures import empty_reality, project_alpha
from .render import render_csv
from .views import search
from .extraction import OpenAIResponsesExtractor
from .extraction import apply_approved
from .extraction import batch_from_agent_file
from .review_ui import run_review
from .store import SQLiteStore
from .web import serve
from .discovery import discover
from .connectors import local_file
from .learning import assess_explanation, make_challenge, start_candidates
from .catalog import import_icrs_catalog
from .sky_explorer import write_sky_explorer


def main() -> None:
    parser = argparse.ArgumentParser(description="Search evidence-backed operational representations")
    parser.add_argument("question", nargs="?", help="Question to answer with a representation")
    parser.add_argument("--top", type=int, default=3)
    parser.add_argument("--csv", type=Path)
    parser.add_argument("--extract", type=Path, help="Source text to send for proposal extraction")
    parser.add_argument("--model", help="OpenAI model for --extract")
    parser.add_argument("--review-as", help="Open the one-at-a-time review interface as this person")
    parser.add_argument("--database", type=Path, default=Path("representation_compiler.db"), help="SQLite audit database")
    parser.add_argument("--serve", action="store_true", help="Start the local browser UI")
    parser.add_argument("--port", type=int, default=8000, help="Local browser UI port")
    parser.add_argument("--import-proposals", type=Path, help="Import pending proposals generated by an agent subscription")
    parser.add_argument("--discover", help="Run and persist a structurally diverse representation tournament for the latest approved batch")
    parser.add_argument("--ingest", type=Path, help="Read a local source file and print its normalized source record")
    parser.add_argument("--learn", help="Start a learning session for the latest approved batch")
    parser.add_argument("--familiarity", default="new", help="Learner familiarity: new, partial, or confident")
    parser.add_argument("--explain", nargs=2, metavar=("SESSION_ID", "ANSWER"), help="Submit an explain-back answer")
    parser.add_argument("--confidence", type=float, default=.5, help="Self-rated confidence from 0 to 1")
    parser.add_argument("--import-star-catalog", type=Path, help="Import CSV with ra_deg and dec_deg columns into a portable astronomy notebook")
    parser.add_argument("--notebook-output", type=Path, help="Destination JSON file for --import-star-catalog")
    parser.add_argument("--catalog-source-uri", help="Stable URI to store in the portable catalog notebook")
    parser.add_argument("--sky-explorer", type=Path, help="Notebook JSON containing derived vectors to render as an interactive sky explorer")
    parser.add_argument("--explorer-output", type=Path, help="Destination HTML file for an interactive sky explorer")
    args = parser.parse_args()
    model = project_alpha()
    if args.serve:
        serve(str(args.database), args.port)
        return
    if args.import_star_catalog:
        if not args.notebook_output:
            parser.error("--import-star-catalog requires --notebook-output")
        imported = import_icrs_catalog(args.import_star_catalog, args.catalog_source_uri)
        output = imported.notebook.write_json(args.notebook_output)
        explorer = write_sky_explorer(imported.notebook.to_dict(), args.explorer_output) if args.explorer_output else None
        print(f"Imported {imported.row_count} catalog rows\nMaximum unit-norm error: {imported.max_unit_norm_error:.3g}\nNotebook: {output}" + (f"\nExplorer: {explorer}" if explorer else ""))
        return
    if args.sky_explorer:
        if not args.explorer_output:
            parser.error("--sky-explorer requires --explorer-output")
        notebook = json.loads(args.sky_explorer.read_text(encoding="utf-8"))
        output = write_sky_explorer(notebook, args.explorer_output)
        print(f"Explorer: {output}")
        return
    if args.ingest:
        source = local_file(args.ingest)
        print(json.dumps(source.__dict__, indent=2))
        return
    if args.learn:
        store = SQLiteStore(args.database)
        try:
            rows = store.list_batches()
            if not rows: parser.error("--learn requires an imported and approved batch")
            batch_id = rows[0]["id"]
            model = store.hydrate_committed_claims(batch_id, empty_reality())
            if not model.assertions: parser.error("--learn requires at least one approved claim")
            session_id = store.create_learning_session(batch_id, args.learn, args.familiarity, args.learn)
            candidates, challenge = start_candidates(model, args.learn), make_challenge(model)
        finally:
            store.close()
        print(json.dumps({"session_id": session_id, "challenge": challenge.__dict__, "candidates": [item.to_dict() for item in candidates[:3]]}, indent=2))
        return
    if args.explain:
        session_id, answer = args.explain
        store = SQLiteStore(args.database)
        try:
            session = store.learning_session(session_id)
            model = store.hydrate_committed_claims(session["batch_id"], empty_reality())
            candidates = start_candidates(model, session["goal"])
            assessment = assess_explanation(answer, make_challenge(model), candidates)
            store.record_explanation(session_id, answer, args.confidence, assessment)
        finally:
            store.close()
        print(json.dumps(assessment.__dict__, indent=2))
        return
    if args.import_proposals:
        payload = json.loads(args.import_proposals.read_text(encoding="utf-8"))
        batch = batch_from_agent_file(payload)
        store = SQLiteStore(args.database)
        try:
            batch_id = store.create_batch(batch.source_id, batch.source_text, "host-agent-subscription", batch)
        finally:
            store.close()
        print(f"Imported {len(batch.proposals)} pending proposals\nAudit batch: {batch_id}\nDatabase: {args.database}")
        return
    if args.discover:
        store = SQLiteStore(args.database)
        try:
            batch_rows = store.list_batches()
            if not batch_rows:
                parser.error("--discover requires an imported proposal batch")
            batch_id = batch_rows[0]["id"]
            model = store.hydrate_committed_claims(batch_id, empty_reality())
            if not model.assertions:
                parser.error("--discover requires at least one approved claim")
            candidates = discover(model, args.discover)
            tournament_id = store.record_tournament(batch_id, args.discover, candidates)
        finally:
            store.close()
        print(json.dumps({"tournament_id": tournament_id, "candidates": [item.to_dict() for item in candidates]}, indent=2))
        return
    if args.extract:
        if not args.model:
            parser.error("--extract requires --model")
        batch = OpenAIResponsesExtractor(args.model).extract(args.extract.stem, args.extract.read_text(), [entity.__dict__ for entity in model.entities.values()])
        if args.review_as:
            store = SQLiteStore(args.database)
            try:
                batch_id = store.create_batch(batch.source_id, batch.source_text, args.model, batch)
                run_review(batch, args.review_as, on_review=lambda proposal: store.record_review(batch_id, proposal), on_change=lambda proposal: store.save_proposal(batch_id, proposal))
                print(json.dumps([proposal.__dict__ for proposal in batch.proposals], indent=2, default=str))
                committed = apply_approved(model, batch)
                store.record_commits(batch_id, model, committed)
                print(f"Committed: {committed}\nAudit batch: {batch_id}\nDatabase: {args.database}")
            finally:
                store.close()
        else:
            print(json.dumps([proposal.__dict__ for proposal in batch.proposals], indent=2, default=str))
        return
    if not args.question:
        parser.error("question is required unless --extract is supplied")
    results = search(model, args.question, args.top)
    print(json.dumps([{ "view": x.spec.name, "score": x.score, "why": x.rationale } for x in results], indent=2))
    if args.csv:
        render_csv(model, results[0], args.csv)
        print(f"Wrote {args.csv}")


if __name__ == "__main__":
    main()
