"""Dependency-free interactive projections of a portable understanding notebook."""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def write_notebook_explorer(notebook: dict[str, Any], output: str | Path) -> Path:
    target = Path(output)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_notebook_explorer(notebook), encoding="utf-8")
    return target


def render_notebook_explorer(notebook: dict[str, Any]) -> str:
    title = _escape(str(notebook.get("title", "Understanding notebook")))
    payload = json.dumps(notebook).replace("</", "<\\/")
    return f"""<!doctype html><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>{title}</title>
<style>:root{{--paper:#f5f5f5;--ink:#2d3142;--muted:#4f5d75;--soft:#7a8399;--accent:#eb6c36;--rule:rgba(45,49,66,.14)}}*{{box-sizing:border-box}}body{{max-width:1180px;margin:auto;padding:32px 20px 64px;background:var(--paper);color:var(--ink);font:16px Geist,system-ui,sans-serif}}h1{{font:400 42px Georgia,serif;margin:6px 0}}h2{{font-size:18px}}p{{color:var(--muted);line-height:1.5}}.meta{{font:11px ui-monospace,monospace;letter-spacing:.1em;color:var(--soft);text-transform:uppercase}}.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}}article,.panel{{background:#fff;border:1px solid var(--rule);border-radius:8px;padding:16px}}article.selected{{border:2px solid var(--accent)}}button,textarea,input{{font:inherit;border-radius:6px;padding:8px;border:1px solid #c9d1db}}button{{background:var(--ink);color:#fff;cursor:pointer;margin:8px 4px 0 0}}button.primary{{background:var(--accent);border-color:var(--accent)}}textarea,input{{width:100%;background:#fff}}textarea{{min-height:96px}}.hidden{{display:none}}.diagram{{margin-top:24px}}svg{{width:100%;height:auto;display:block;background:#fff;border:1px solid var(--rule);border-radius:8px}}.layout{{display:grid;grid-template-columns:1fr 260px;gap:20px;align-items:start}}pre{{white-space:pre-wrap;max-height:300px;overflow:auto;font-size:12px}}.node{{cursor:pointer}}@media(max-width:760px){{.layout{{grid-template-columns:1fr}}h1{{font-size:32px}}}}</style>
<main><div class='meta'>Evidence-backed understanding notebook</div><h1>{title}</h1><p id='question'></p><h2>Choose a real representation</h2><div id='candidates' class='grid'></div><section id='visual' class='diagram hidden'><div class='layout'><div><svg id='diagram' viewBox='0 0 1120 560' role='img' aria-labelledby='representation-diagram-title representation-diagram-desc'><title id='representation-diagram-title'>Source-grounded representation</title><desc id='representation-diagram-desc'>An interactive diagram whose nodes and relationships link to source fragments.</desc></svg></div><aside class='panel'><div class='meta'>Evidence</div><h2 id='evidence-title'>Select a node</h2><p id='evidence-copy'>Click a concept to see the exact source fragments behind it.</p></aside></div></section><section id='learn' class='hidden'><h2>Check your understanding</h2><p>Explain the central relationship. What changes if one important relationship disappears?</p><label>Explain it in your own words<textarea id='explanation'></textarea></label><label>Confidence (0–1)<input id='confidence' type='number' min='0' max='1' step='.1' value='.5'></label><button class='primary' id='save'>Add to learning ledger and download notebook</button><p id='result'></p></section><details><summary>Inspect indexed source material</summary><pre id='source'></pre></details></main>
<script>
const notebook={payload},reps=Object.values(notebook.representations).filter(r=>r.family!=='source index');let selected=null,reaction='clicked';const cards=document.querySelector('#candidates'),learn=document.querySelector('#learn'),visual=document.querySelector('#visual'),svg=document.querySelector('#diagram');document.querySelector('#question').textContent=notebook.question;document.querySelector('#source').textContent=JSON.stringify(notebook.derived_data,null,2);const ns='http://www.w3.org/2000/svg';
function esc(v){{const n=document.createElement('span');n.textContent=v;return n.innerHTML}}function el(tag,attrs={{}},text=''){{const n=document.createElementNS(ns,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));n.textContent=text;return n}}
function card(r){{return `<article class="${{selected===r.id?'selected':''}}"><div class="meta">${{esc(r.family)}}</div><h2>${{esc(r.title)}}</h2><p>${{esc(r.makes_easier.join(', '))}}</p><details><summary>Trade-off and test</summary><p><b>Hides:</b> ${{esc(r.discards.join(', '))}}<br>${{esc(r.falsification_test)}}</p></details><button class="primary" onclick="choose('${{r.id}}','clicked')">Show this representation</button><button onclick="choose('${{r.id}}','another_way')">Another way</button></article>`}}function renderCards(){{cards.innerHTML=reps.map(card).join('')}}
function choose(id,kind){{selected=id;reaction=kind;visual.classList.remove('hidden');learn.classList.remove('hidden');renderCards();draw();visual.scrollIntoView({{behavior:'smooth'}})}}window.choose=choose;
function layout(nodes,kind){{if(kind==='timeline')return nodes.map((n,i)=>({{...n,x:40+(i%5)*216,y:240+Math.floor(i/5)*144}}));if(kind==='state-machine')return nodes.map((n,i)=>({{...n,x:56+(i%4)*264,y:144+Math.floor(i/4)*176}}));return nodes.map((n,i)=>({{...n,x:56+(i%3)*352,y:80+Math.floor(i/3)*120}}))}}
function draw(){{svg.replaceChildren();const rep=notebook.representations[selected],graph=notebook.graphs[rep.graph_id],nodes=layout(graph.nodes,selected);svg.append(el('rect',{{width:1120,height:560,fill:'#f5f5f5'}}));svg.append(el('text',{{x:40,y:40,fill:'#7a8399','font-size':12,'font-family':'ui-monospace,monospace','letter-spacing':1.4}},rep.title.toUpperCase()+' · SOURCE-GROUNDED'));const byId=Object.fromEntries(nodes.map(n=>[n.id,n]));for(const edge of graph.edges){{const a=byId[edge.source_id],b=byId[edge.target_id];if(!a||!b)continue;const ay=a.y+56,bx=b.x,mid=(a.x+200+bx)/2;svg.append(el('path',{{d:`M ${{a.x+200}} ${{ay}} H ${{mid}} Q ${{mid+8}} ${{ay}} ${{mid+8}} ${{ay+8}} V ${{b.y+28}} Q ${{mid+8}} ${{b.y+36}} ${{mid+16}} ${{b.y+36}} H ${{bx}}`,fill:'none',stroke:'#4f5d75','stroke-width':1.2,'marker-end':'url(#arrow)'}}));svg.append(el('text',{{x:mid,y:Math.min(ay,b.y+28)-12,fill:'#7a8399','font-size':10,'font-family':'ui-monospace,monospace','text-anchor':'middle'}},edge.relation.toUpperCase()))}}const defs=el('defs');const marker=el('marker',{{id:'arrow',markerWidth:8,markerHeight:6,refX:7,refY:3,orient:'auto'}});marker.append(el('polygon',{{points:'0 0,8 3,0 6',fill:'#4f5d75'}}));defs.append(marker);svg.insertBefore(defs,svg.firstChild);for(const node of nodes){{const g=el('g',{{class:'node',tabindex:0}});g.append(el('rect',{{x:node.x,y:node.y,width:200,height:112,rx:8,fill:node.id==='model-server'?'rgba(235,108,54,.08)':'#fff',stroke:node.id==='model-server'?'#eb6c36':'#2d3142','stroke-width':node.id==='model-server'?2:1}}));g.append(el('text',{{x:node.x+16,y:node.y+24,fill:'#7a8399','font-size':10,'font-family':'ui-monospace,monospace'}},node.kind.toUpperCase()));g.append(el('text',{{x:node.x+16,y:node.y+56,fill:'#2d3142','font-size':16,'font-weight':600}},node.label));g.append(el('text',{{x:node.x+16,y:node.y+84,fill:'#4f5d75','font-size':10,'font-family':'ui-monospace,monospace'}},`${{node.evidence_ids.length}} SOURCE FRAGMENT(S)`));g.addEventListener('click',()=>evidence(node));g.addEventListener('keydown',e=>{{if(e.key==='Enter')evidence(node)}});svg.append(g)}}
function evidence(node){{const rows=Object.values(notebook.derived_data)[0].rows,ids=new Set(node.evidence_ids),quotes=rows.filter(r=>ids.has(r.fragment_id)||ids.has(r.row_id)||ids.has(r.path)).map(r=>r.text||JSON.stringify(r)).slice(0,3);document.querySelector('#evidence-title').textContent=node.label;document.querySelector('#evidence-copy').textContent=quotes.join('\n\n')||'Source fragment unavailable.'}}
document.querySelector('#save').onclick=()=>{{if(!selected)return;const answer=document.querySelector('#explanation').value.trim(),next=reaction==='another_way'?'concept-matrix':selected==='mechanism-map'?'state-machine':'mechanism-map';notebook.learning_ledger=notebook.learning_ledger||[];notebook.learning_ledger.push({{goal:notebook.question,representation_id:selected,reaction,explain_back:answer,confidence:Number(document.querySelector('#confidence').value),challenge:'Explain the central relationship. What changes if it disappears?',gaps:[],recommended_representation_id:next}});const blob=new Blob([JSON.stringify(notebook,null,2)],{{type:'application/json'}}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=(notebook.id||'understanding-notebook')+'.json';link.click();URL.revokeObjectURL(url);document.querySelector('#result').textContent=`Saved. Next recommended view: ${{next}}.`}};renderCards();
</script>"""


def _escape(value: str) -> str:
    return value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")
